name: Graphics Tests Workflow
description: 'Graphics tests action to run the MonoGame Framework graphics tests'
inputs:
  platform:
    description: 'Platform to run the action on'
    required: true
  shell:
    description: 'Shell to use for the action'
    required: true
  filter:
    description: 'Filter to apply to the tests'
    required: true

runs:
  using: "composite"
  steps:
      - name: Download Nuget
        uses: actions/download-artifact@v4
        with:
          name: nuget-${{ inputs.platform }}
          path: Artifacts/NuGet

      - name: Download tests-tools
        uses: actions/download-artifact@v4
        with:
          name: tests-tools-${{ inputs.platform }}
          path: tests tools

      - name: Download tests-desktopgl
        uses: actions/download-artifact@v4
        with:
          name: tests-desktopgl-${{ inputs.platform }}
          path: tests-desktopgl

      - name: Download tests-windowsdx
        uses: actions/download-artifact@v4
        with:
          name: tests-windowsdx-${{ inputs.platform }}
          path: tests-windowsdx
        if: ${{ inputs.platform == 'windows' }}

      - name: Run Graphics.BlendStateTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.BlendStateTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.DepthStencilStateTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.DepthStencilStateTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.EffectTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.EffectTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.GraphicsAdapterTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.GraphicsAdapterTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      # This test hangs on MacOS?
      - name: Run Graphics.GraphicsDeviceTest Tests
        if: ${{ inputs.platform != 'macos' }}
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.GraphicsDeviceTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.IndexBufferTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.IndexBufferTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.MiscellaneousTests Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.MiscellaneousTests
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.ModelTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.ModelTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.OcclusionQueryTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.OcclusionQueryTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.RasterizerStateTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.RasterizerStateTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.RenderTarget2DTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.RenderTarget2DTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.RenderTargetCubeTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.RenderTargetCubeTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.SamplerStateTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.SamplerStateTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.ScissorRectangleTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.ScissorRectangleTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.ShaderTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.ShaderTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.SpriteBatchTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.SpriteBatchTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.SpriteFontTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.SpriteFontTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.Texture2DNonVisualTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.Texture2DNonVisualTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.Texture2DTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.Texture2DTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.Texture3DNonVisualTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.Texture3DNonVisualTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.Texture3DTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.Texture3DTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.TextureCubeTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.TextureCubeTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.VertexBufferTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.VertexBufferTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}

      - name: Run Graphics.ViewportTest Tests
        run: dotnet MonoGame.Tests.dll --timeout=300000 --test MonoGame.Tests.Graphics.ViewportTest
        working-directory: tests-desktopgl
        shell: ${{ inputs.shell }}