name: Deploy

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Push Nugets
        run: dotnet run --project build/Build.csproj -- --target=Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          MARKETPLACE_PAT: ${{ secrets.MARKETPLACE_PAT }}

      - name: Make a Release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          name: "MonoGame ${{ github.ref_name }}"
          tag: ${{ github.ref_name }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: "nugets/*.nupkg;vsix/MonoGame.Templates.VSExtension.vsix"
          token: ${{ secrets.GITHUB_TOKEN }}
