name: Main MonoGame build workflow

on:
  pull_request:

  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Runs preliminary build and validation on the self-hosted runners to ensure build cohoesion
  build-and-validate:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            shell: cmd
          - os: macos-latest
            platform: macos
            shell: bash
          - os: ubuntu-latest
            platform: linux
            shell: bash
    runs-on: ${{ matrix.os }}
    env:
      CI: true    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive      

      - uses: ./.github/actions/checkdependencies
        name: Check Dependencies
        with:
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}

      - uses: ./.github/actions/build
        name: Build
        with:
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}

  test:
    # Deeper build and test cycle on self-hosted runners with deploy if successful
    needs: [ build-and-validate ]
    strategy:
      matrix:
        include:
          - os: windows
            platform: windows
            shell: cmd
          - os: macos
            platform: macos
            shell: bash
          - os: ubuntu-latest
            platform: linux
            shell: bash
            filter: --where="Category != Audio"
    runs-on: ${{ matrix.os }}
    env:
      CI: true    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive      

      - uses: ./.github/actions/checkdependencies
        name: Check Dependencies
        with:
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}

      - uses: ./.github/actions/build
        name: Build
        with:
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}

      - uses: ./.github/actions/tests
        name: Tests
        with:
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}
          filter: ${{ matrix.filter }}

      - uses: ./.github/actions/tests-graphics
        name: Graphics Tests
        with:
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}
          filter: ${{ matrix.filter }}
        if: ${{ runner.environment != 'github-hosted'}}

  deploy:
    # Deploy if conditions are met
    needs: [ test ]
    runs-on: ubuntu-latest
    env:
      CI: true    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          shell: bash
        if: ${{ github.event_name == 'push' && success() }}      