name: Main MonoGame build workflow

on: [push, pull_request]

jobs:
  build-and-deploy:
    strategy:
      matrix:
        include:
          - os: windows
            platform: windows
            shell: cmd
          - os: macos
            platform: macos
            shell: bash
          - os: ubuntu-latest
            platform: linux
            shell: bash
            filter: --where="Category != Audio"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive      
      - uses: ./.github/actions/checkdependencies
        name: Check Dependencies
        with:
          os: ${{ matrix.os }}
      - uses: ./.github/actions/build
        name: Build
        with:
          os: ${{ matrix.os }}
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}
          filter: ${{ matrix.filter }}

      - uses: ./.github/actions/tests
        name: Tests
        with:
          os: ${{ matrix.os }}
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}
          filter: ${{ matrix.filter }}

      - uses: ./.github/actions/tests-graphics
        name: Graphics Tests
        with:
          os: ${{ matrix.os }}
          platform: ${{ matrix.platform }}
          shell: ${{ matrix.shell }}
          filter: ${{ matrix.filter }}
        if: ${{ runner.environment != 'github-hosted'}}

      - uses: ./.github/actions/deploy
        name: Deploy
        with:
          os: ${{ matrix.os }}
        if: ${{ github.event_name == 'push' && success() }}